# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ksercs/cpp-course/huffman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ksercs/cpp-course/huffman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ksercs/cpp-course/huffman/CMakeFiles /home/ksercs/cpp-course/huffman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ksercs/cpp-course/huffman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MAIN

# Build rule for target.
MAIN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MAIN
.PHONY : MAIN

# fast build rule for target.
MAIN/fast:
	$(MAKE) -f CMakeFiles/MAIN.dir/build.make CMakeFiles/MAIN.dir/build
.PHONY : MAIN/fast

#=============================================================================
# Target rules for targets named HUFFMAN

# Build rule for target.
HUFFMAN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HUFFMAN
.PHONY : HUFFMAN

# fast build rule for target.
HUFFMAN/fast:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/build
.PHONY : HUFFMAN/fast

#=============================================================================
# Target rules for targets named TESTING

# Build rule for target.
TESTING: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TESTING
.PHONY : TESTING

# fast build rule for target.
TESTING/fast:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/build
.PHONY : TESTING/fast

gtest/gtest-all.o: gtest/gtest-all.cc.o

.PHONY : gtest/gtest-all.o

# target to build an object file
gtest/gtest-all.cc.o:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/gtest/gtest-all.cc.o
.PHONY : gtest/gtest-all.cc.o

gtest/gtest-all.i: gtest/gtest-all.cc.i

.PHONY : gtest/gtest-all.i

# target to preprocess a source file
gtest/gtest-all.cc.i:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/gtest/gtest-all.cc.i
.PHONY : gtest/gtest-all.cc.i

gtest/gtest-all.s: gtest/gtest-all.cc.s

.PHONY : gtest/gtest-all.s

# target to generate assembly for a file
gtest/gtest-all.cc.s:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/gtest/gtest-all.cc.s
.PHONY : gtest/gtest-all.cc.s

gtest/gtest_main.o: gtest/gtest_main.cc.o

.PHONY : gtest/gtest_main.o

# target to build an object file
gtest/gtest_main.cc.o:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/gtest/gtest_main.cc.o
.PHONY : gtest/gtest_main.cc.o

gtest/gtest_main.i: gtest/gtest_main.cc.i

.PHONY : gtest/gtest_main.i

# target to preprocess a source file
gtest/gtest_main.cc.i:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/gtest/gtest_main.cc.i
.PHONY : gtest/gtest_main.cc.i

gtest/gtest_main.s: gtest/gtest_main.cc.s

.PHONY : gtest/gtest_main.s

# target to generate assembly for a file
gtest/gtest_main.cc.s:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/gtest/gtest_main.cc.s
.PHONY : gtest/gtest_main.cc.s

lib/huffman.o: lib/huffman.cpp.o

.PHONY : lib/huffman.o

# target to build an object file
lib/huffman.cpp.o:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/huffman.cpp.o
.PHONY : lib/huffman.cpp.o

lib/huffman.i: lib/huffman.cpp.i

.PHONY : lib/huffman.i

# target to preprocess a source file
lib/huffman.cpp.i:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/huffman.cpp.i
.PHONY : lib/huffman.cpp.i

lib/huffman.s: lib/huffman.cpp.s

.PHONY : lib/huffman.s

# target to generate assembly for a file
lib/huffman.cpp.s:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/huffman.cpp.s
.PHONY : lib/huffman.cpp.s

lib/my_reader.o: lib/my_reader.cpp.o

.PHONY : lib/my_reader.o

# target to build an object file
lib/my_reader.cpp.o:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/my_reader.cpp.o
.PHONY : lib/my_reader.cpp.o

lib/my_reader.i: lib/my_reader.cpp.i

.PHONY : lib/my_reader.i

# target to preprocess a source file
lib/my_reader.cpp.i:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/my_reader.cpp.i
.PHONY : lib/my_reader.cpp.i

lib/my_reader.s: lib/my_reader.cpp.s

.PHONY : lib/my_reader.s

# target to generate assembly for a file
lib/my_reader.cpp.s:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/my_reader.cpp.s
.PHONY : lib/my_reader.cpp.s

lib/my_writer.o: lib/my_writer.cpp.o

.PHONY : lib/my_writer.o

# target to build an object file
lib/my_writer.cpp.o:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/my_writer.cpp.o
.PHONY : lib/my_writer.cpp.o

lib/my_writer.i: lib/my_writer.cpp.i

.PHONY : lib/my_writer.i

# target to preprocess a source file
lib/my_writer.cpp.i:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/my_writer.cpp.i
.PHONY : lib/my_writer.cpp.i

lib/my_writer.s: lib/my_writer.cpp.s

.PHONY : lib/my_writer.s

# target to generate assembly for a file
lib/my_writer.cpp.s:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/my_writer.cpp.s
.PHONY : lib/my_writer.cpp.s

lib/tree.o: lib/tree.cpp.o

.PHONY : lib/tree.o

# target to build an object file
lib/tree.cpp.o:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/tree.cpp.o
.PHONY : lib/tree.cpp.o

lib/tree.i: lib/tree.cpp.i

.PHONY : lib/tree.i

# target to preprocess a source file
lib/tree.cpp.i:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/tree.cpp.i
.PHONY : lib/tree.cpp.i

lib/tree.s: lib/tree.cpp.s

.PHONY : lib/tree.s

# target to generate assembly for a file
lib/tree.cpp.s:
	$(MAKE) -f CMakeFiles/HUFFMAN.dir/build.make CMakeFiles/HUFFMAN.dir/lib/tree.cpp.s
.PHONY : lib/tree.cpp.s

test/huffman_testing.o: test/huffman_testing.cpp.o

.PHONY : test/huffman_testing.o

# target to build an object file
test/huffman_testing.cpp.o:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/test/huffman_testing.cpp.o
.PHONY : test/huffman_testing.cpp.o

test/huffman_testing.i: test/huffman_testing.cpp.i

.PHONY : test/huffman_testing.i

# target to preprocess a source file
test/huffman_testing.cpp.i:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/test/huffman_testing.cpp.i
.PHONY : test/huffman_testing.cpp.i

test/huffman_testing.s: test/huffman_testing.cpp.s

.PHONY : test/huffman_testing.s

# target to generate assembly for a file
test/huffman_testing.cpp.s:
	$(MAKE) -f CMakeFiles/TESTING.dir/build.make CMakeFiles/TESTING.dir/test/huffman_testing.cpp.s
.PHONY : test/huffman_testing.cpp.s

util/main.o: util/main.cpp.o

.PHONY : util/main.o

# target to build an object file
util/main.cpp.o:
	$(MAKE) -f CMakeFiles/MAIN.dir/build.make CMakeFiles/MAIN.dir/util/main.cpp.o
.PHONY : util/main.cpp.o

util/main.i: util/main.cpp.i

.PHONY : util/main.i

# target to preprocess a source file
util/main.cpp.i:
	$(MAKE) -f CMakeFiles/MAIN.dir/build.make CMakeFiles/MAIN.dir/util/main.cpp.i
.PHONY : util/main.cpp.i

util/main.s: util/main.cpp.s

.PHONY : util/main.s

# target to generate assembly for a file
util/main.cpp.s:
	$(MAKE) -f CMakeFiles/MAIN.dir/build.make CMakeFiles/MAIN.dir/util/main.cpp.s
.PHONY : util/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... MAIN"
	@echo "... HUFFMAN"
	@echo "... TESTING"
	@echo "... rebuild_cache"
	@echo "... gtest/gtest-all.o"
	@echo "... gtest/gtest-all.i"
	@echo "... gtest/gtest-all.s"
	@echo "... gtest/gtest_main.o"
	@echo "... gtest/gtest_main.i"
	@echo "... gtest/gtest_main.s"
	@echo "... lib/huffman.o"
	@echo "... lib/huffman.i"
	@echo "... lib/huffman.s"
	@echo "... lib/my_reader.o"
	@echo "... lib/my_reader.i"
	@echo "... lib/my_reader.s"
	@echo "... lib/my_writer.o"
	@echo "... lib/my_writer.i"
	@echo "... lib/my_writer.s"
	@echo "... lib/tree.o"
	@echo "... lib/tree.i"
	@echo "... lib/tree.s"
	@echo "... test/huffman_testing.o"
	@echo "... test/huffman_testing.i"
	@echo "... test/huffman_testing.s"
	@echo "... util/main.o"
	@echo "... util/main.i"
	@echo "... util/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

